package fxml;

import core.Logic;
import core.Main;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.SelectionMode;
import javafx.scene.input.MouseEvent;

import java.io.File;
import java.io.FilenameFilter;
import java.util.Arrays;
import java.util.List;

/**
 * Controls and handles the LoadGame scene
 *
 * @author Joseph Omar
 * @version 1.0
 */
public class LoadGameController {
    @FXML
    private Button cmdRefresh;
    @FXML
    private Button cmdLoad;
    @FXML
    private Button cmdCancel;
    @FXML
    private ListView lstSaves;

    private File selected;

    /**
     * Initialises the window, loading a list of save files and putting them into a listview
     */
    public LoadGameController() {
        lstSaves.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);
        setListData();
    }

    /**
     * Finds all the files in the save folder that have the extension .labyrinth and adds them to a list
     *
     * @return List of save files
     */
    private List<File> getSaves() {
        File dir = new File("/saves");
        if (!dir.exists()) {
            dir.mkdir();
        }
        File[] dirFilteredContents = dir.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.endsWith(".labyrinth");
            }
        });
        List<File> dirContentsList = Arrays.asList(dirFilteredContents);
        return dirContentsList;
    }

    /**
     * Sets the collection of items that is shown on the listbox to the list generated by getSaves()
     */
    private void setListData() {
        ObservableList<File> observableList = FXCollections.observableList(getSaves());
        lstSaves.setItems(observableList);
    }

    /**
     * refreshes the list content
     *
     * @param actionEvent
     */
    public void cmdRefreshClick(ActionEvent actionEvent) {
        setListData();
    }


    /**
     * Handles the event that occurs when a list item is selected
     *
     * @param mouseEvent
     */
    public void lstSavesClick(MouseEvent mouseEvent) {
        selected = (File) lstSaves.getSelectionModel().getSelectedItem();
    }

    /**
     * Handles the event that occurs when load game is clicked. It checks if an item is selected and if it is, sends the selected save file to the Logic class
     *
     * @param actionEvent
     */
    public void cmdLoadClick(ActionEvent actionEvent) {
        if (selected == null && lstSaves.getSelectionModel().getSelectedItem() == null) {
            Main.showError("A Save file is needed for loading a game from file. Please select a Save to load.", "No Save Selected", "Load Save", false);
        } else {
            Logic.createGame(selected);
        }
    }
}
